version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "Installing dependencies"
      - cd uploads_notification
      - if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
  build:
    commands:
      - echo "Running sam build"
      - cd uploads_notification 
      - sam build
      - echo "Running sam package"
      - sam package --s3-bucket akmal-makhmudov-bucket --output-template-file ../packaged.yaml
artifacts:
  files:
    - packaged.yaml
