version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "Installing dependencies"
      - cd uploads_notification
      - if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - cd ..
  build:
    commands:
      - echo "Running sam build"
      - sam build --template-file uploads_notification/template.yaml
      - echo "Running sam package"
      - sam package --template-file uploads_notification/template.yaml --s3-bucket akmal-makhmudov-bucket --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
